import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Loader from "../(components)/Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased select-none`}>
        <Suspense fallback={<Loader/>}>
        {children}
        </Suspense>
      </body>
    </html>
  );
}
